version: '3'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: khs08280
      MYSQL_DATABASE: triptalk
      MYSQL_USER: spring_server
      MYSQL_PASSWORD: khs08280
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    image: triptalk-registry.kr.ncr.ntruss.com/triptalk-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql  # app 서비스가 mysql 서비스에 의존하도록 설정
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/triptalk?serverTimezone=UTC&characterEncoding=UTF-8  # 중요: mysql 서비스 이름을 호스트로 사용
      - SPRING_DATASOURCE_USERNAME=spring_server
      - SPRING_DATASOURCE_PASSWORD=khs08280
      - SERVER_SSL_ENABLED=false
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  mysql-data: